In [1]:
'''
First, we download the datasets using Kaggle API using the following command line in the Terminal
[to install the kaggle onto local PC]
C:\> pip install kaggle
[to download the audigle datasets from kaggle]
C:\> #!/bin/bash kaggle datasets download snehangsude/audible-dataset

We will got the .zip file so we will unzip the file using built-in command
C:\> -xf audible-dataset.zip
'''

'\nFirst, we download the datasets using Kaggle API using the following command line in the Terminal\n[to install the kaggle onto local PC]\nC:\\> pip install kaggle\n[to download the audigle datasets from kaggle]\nC:\\> #!/bin/bash kaggle datasets download snehangsude/audible-dataset\n\nWe will got the .zip file so we will unzip the file using built-in command\nC:\\> -xf audible-dataset.zip\n'

In [2]:
# import the relevant package
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
# load the datasets into notebook
data = pd.read_csv('audible_uncleaned.csv')

In [4]:
# try read the first few rows of the dataset using df.head() method
# found some repetitive strings in some particular columns, which we will clean it later on
data.head()

name                     author  \
0                  Geronimo Stilton #11 & #12  Writtenby:GeronimoStilton   
1                            The Burning Maze      Writtenby:RickRiordan   
2                                The Deep End       Writtenby:JeffKinney   
3                        Daughter of the Deep      Writtenby:RickRiordan   
4  The Lightning Thief: Percy Jackson, Book 1      Writtenby:RickRiordan   

                    narrator                time releasedate language  \
0      Narratedby:BillLobely   2 hrs and 20 mins    04-08-08  English   
1   Narratedby:RobbieDaymond   13 hrs and 8 mins    01-05-18  English   
2      Narratedby:DanRussell    2 hrs and 3 mins    06-11-20  English   
3  Narratedby:SoneelaNankani  11 hrs and 16 mins    05-10-21  English   
4  Narratedby:JesseBernstein              10 hrs    13-01-10  English   

                           stars   price  
0     5 out of 5 stars34 ratings  468.00  
1   4.5 out of 5 stars41 ratings  820.00  
2   4.5 out of 5 stars38 ratings  410.00  
3   4.5 out of 5 stars12 ratings  615.00  
4  4.5 out of 5 stars181 ratings  820.00

In [5]:
# try find out the data types and possible null values in each column using info() method
# the datatype of all columns is an object, no null values identified
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87489 entries, 0 to 87488
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   name         87489 non-null  object
 1   author       87489 non-null  object
 2   narrator     87489 non-null  object
 3   time         87489 non-null  object
 4   releasedate  87489 non-null  object
 5   language     87489 non-null  object
 6   stars        87489 non-null  object
 7   price        87489 non-null  object
dtypes: object(8)
memory usage: 5.3+ MB


In [6]:
# check if there's null value in datasets, no null values found
data.isnull().sum()

name           0
author         0
narrator       0
time           0
releasedate    0
language       0
stars          0
price          0
dtype: int64

In [7]:
# try to split the columnn
newauthor = data['author'].str.split(':',expand=True)
newauthor.head()

0                1
0  Writtenby  GeronimoStilton
1  Writtenby      RickRiordan
2  Writtenby       JeffKinney
3  Writtenby      RickRiordan
4  Writtenby      RickRiordan

In [8]:
data['author'] = newauthor[1]
data.head()

name           author  \
0                  Geronimo Stilton #11 & #12  GeronimoStilton   
1                            The Burning Maze      RickRiordan   
2                                The Deep End       JeffKinney   
3                        Daughter of the Deep      RickRiordan   
4  The Lightning Thief: Percy Jackson, Book 1      RickRiordan   

                    narrator                time releasedate language  \
0      Narratedby:BillLobely   2 hrs and 20 mins    04-08-08  English   
1   Narratedby:RobbieDaymond   13 hrs and 8 mins    01-05-18  English   
2      Narratedby:DanRussell    2 hrs and 3 mins    06-11-20  English   
3  Narratedby:SoneelaNankani  11 hrs and 16 mins    05-10-21  English   
4  Narratedby:JesseBernstein              10 hrs    13-01-10  English   

                           stars   price  
0     5 out of 5 stars34 ratings  468.00  
1   4.5 out of 5 stars41 ratings  820.00  
2   4.5 out of 5 stars38 ratings  410.00  
3   4.5 out of 5 stars12 ratings  615.00  
4  4.5 out of 5 stars181 ratings  820.00

In [9]:
# repeat this steps into narrator columns
newnarrator = data['narrator'].str.split(':',expand=True)
newnarrator.head()

0               1
0  Narratedby      BillLobely
1  Narratedby   RobbieDaymond
2  Narratedby      DanRussell
3  Narratedby  SoneelaNankani
4  Narratedby  JesseBernstein

In [10]:
data['narrator'] = newnarrator[1]
data.head()

name           author  \
0                  Geronimo Stilton #11 & #12  GeronimoStilton   
1                            The Burning Maze      RickRiordan   
2                                The Deep End       JeffKinney   
3                        Daughter of the Deep      RickRiordan   
4  The Lightning Thief: Percy Jackson, Book 1      RickRiordan   

         narrator                time releasedate language  \
0      BillLobely   2 hrs and 20 mins    04-08-08  English   
1   RobbieDaymond   13 hrs and 8 mins    01-05-18  English   
2      DanRussell    2 hrs and 3 mins    06-11-20  English   
3  SoneelaNankani  11 hrs and 16 mins    05-10-21  English   
4  JesseBernstein              10 hrs    13-01-10  English   

                           stars   price  
0     5 out of 5 stars34 ratings  468.00  
1   4.5 out of 5 stars41 ratings  820.00  
2   4.5 out of 5 stars38 ratings  410.00  
3   4.5 out of 5 stars12 ratings  615.00  
4  4.5 out of 5 stars181 ratings  820.00

In [11]:
# we will split the column of timme which we use whitespace as delimiter
newtime = data['time'].str.split(' ',expand=True)
newtime.head()

0    1     2     3     4
0   2  hrs   and    20  mins
1  13  hrs   and     8  mins
2   2  hrs   and     3  mins
3  11  hrs   and    16  mins
4  10  hrs  None  None  None

In [12]:
newtime.count()

0    87489
1    87489
2    72801
3    72801
4    72740
dtype: int64

In [13]:
# write loops to clean up the data
for i in range(len(newtime)):
    if newtime.iloc[i][1] == 'mins' or newtime.iloc[i][1] == 'min':
        newtime.iloc[i][3] = newtime.iloc[i][0]
        newtime.iloc[i][0] = 0

    if newtime.iloc[i][0] == "Less":
        newtime.iloc[i][0] = 0
        newtime.iloc[i][3] = 1

    if newtime.iloc[i][3] == None:
        newtime.iloc[i][3] = 0

# clean up the time scale unit
newtime[1] = 'hrs'
newtime[4] = 'mins'

# convert data types from str to int
newtime[0] = newtime[0].astype(int)
newtime[3] = newtime[3].astype(int)

In [14]:
newtime[0].unique()

array([  2,  13,  11,  10,  12,   8,   5,   6,  14,  16,  23,   7,   1,
         3,   0,  17,  22,   9,   4,  15,  20,  26,  19,  33,  24,  64,
        18, 122,  55,  30,  21,  29,  31,  40,  38,  27,  25,  59,  52,
        37,  42,  28,  45,  34,  41,  43,  32,  51,  54,  49,  36,  35,
        44,  50,  48,  53,  39,  81, 111,  57,  67, 126,  47,  83,  61,
        60,  46,  63,  70,  92,  58,  62,  71,  73,  87,  65,  74, 102,
       143,  56,  95,  72,  82,  78,  69,  75,  98,  85])

In [15]:
newtime[3].unique()

array([20,  8,  3, 16,  0, 35, 23, 32, 56, 22, 48,  1, 58, 55, 25,  4, 41,
       18, 42, 12, 29, 46, 37,  9, 44, 53, 28, 26, 13, 43, 39, 31, 19, 33,
       51, 47, 24,  2, 10, 49, 27, 34, 54,  6, 30, 38, 36, 50, 11, 52,  5,
       45, 21, 57, 15, 17, 59, 40,  7, 14])

In [16]:
total_mins = (newtime[0]*60) + (newtime[3]) # we will put this onto the dataframe
total_mins.head()

0    140
1    788
2    123
3    676
4    600
dtype: int32

In [17]:
newtime[1].unique()

array(['hrs'], dtype=object)

In [18]:
newtime[4].unique()

array(['mins'], dtype=object)

In [19]:
# split up the stars and reviews
newstars = data['stars'].str.split('stars',expand=True)
newstars.head()

0            1
0    5 out of 5    34 ratings
1  4.5 out of 5    41 ratings
2  4.5 out of 5    38 ratings
3  4.5 out of 5    12 ratings
4  4.5 out of 5   181 ratings

In [20]:
newscores = newstars[0].str.split(' ',expand=True)[0]

In [21]:
newscores.replace(to_replace='Not',value=np.nan,inplace=True) # change it to NaN so it could be vectorized

In [22]:
newscores = newscores.astype(float)

In [23]:
newscores.unique()

array([5. , 4.5, 4. , nan, 3.5, 3. , 1. , 2. , 2.5, 1.5])

In [24]:
newratings = newstars[1].str.split(' ',expand=True)[0]

In [25]:
newratings.fillna(value=0, inplace=True)

In [26]:
newratings

0         34
1         41
2         38
3         12
4        181
        ... 
87484      0
87485      0
87486      0
87487      0
87488      0
Name: 0, Length: 87489, dtype: object

In [27]:
# put the cleaned data onto the main datasets
# time (hrs and mins)
data['duration'] = total_mins

# ratings and reviews
data['ratings'] = newscores
data['reviews'] = newratings

In [28]:
data.head()

name           author  \
0                  Geronimo Stilton #11 & #12  GeronimoStilton   
1                            The Burning Maze      RickRiordan   
2                                The Deep End       JeffKinney   
3                        Daughter of the Deep      RickRiordan   
4  The Lightning Thief: Percy Jackson, Book 1      RickRiordan   

         narrator                time releasedate language  \
0      BillLobely   2 hrs and 20 mins    04-08-08  English   
1   RobbieDaymond   13 hrs and 8 mins    01-05-18  English   
2      DanRussell    2 hrs and 3 mins    06-11-20  English   
3  SoneelaNankani  11 hrs and 16 mins    05-10-21  English   
4  JesseBernstein              10 hrs    13-01-10  English   

                           stars   price  duration  ratings reviews  
0     5 out of 5 stars34 ratings  468.00       140      5.0      34  
1   4.5 out of 5 stars41 ratings  820.00       788      4.5      41  
2   4.5 out of 5 stars38 ratings  410.00       123      4.5      38  
3   4.5 out of 5 stars12 ratings  615.00       676      4.5      12  
4  4.5 out of 5 stars181 ratings  820.00       600      4.5     181

In [29]:
# Replace the free price into 0
data['price'].replace('Free',0)

0        468.00
1        820.00
2        410.00
3        615.00
4        820.00
          ...  
87484    596.00
87485    820.00
87486    938.00
87487    680.00
87488    569.00
Name: price, Length: 87489, dtype: object

In [30]:
# filter the dates
data = data[data['releasedate'] <= '2024-10-11']
data.head()

name           author  \
0                  Geronimo Stilton #11 & #12  GeronimoStilton   
1                            The Burning Maze      RickRiordan   
2                                The Deep End       JeffKinney   
3                        Daughter of the Deep      RickRiordan   
4  The Lightning Thief: Percy Jackson, Book 1      RickRiordan   

         narrator                time releasedate language  \
0      BillLobely   2 hrs and 20 mins    04-08-08  English   
1   RobbieDaymond   13 hrs and 8 mins    01-05-18  English   
2      DanRussell    2 hrs and 3 mins    06-11-20  English   
3  SoneelaNankani  11 hrs and 16 mins    05-10-21  English   
4  JesseBernstein              10 hrs    13-01-10  English   

                           stars   price  duration  ratings reviews  
0     5 out of 5 stars34 ratings  468.00       140      5.0      34  
1   4.5 out of 5 stars41 ratings  820.00       788      4.5      41  
2   4.5 out of 5 stars38 ratings  410.00       123      4.5      38  
3   4.5 out of 5 stars12 ratings  615.00       676      4.5      12  
4  4.5 out of 5 stars181 ratings  820.00       600      4.5     181

In [31]:
data.shape

(57709, 11)